[project]
name = "suzaku"
version = "0.1.6"
description = "Yet another GUI lib, looks and performs better than tkinter."
keywords = ["suzaku","future","lightweight","gui","framework"]
authors = [
    {name = "XiangQinxi",email = "XiangQinxi@outlook.com"},
    {name = "rgzz666", email = "tt1224@hotmail.com"},
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "skia-python",
    "glfw",
    "pyopengl",
]
license = "MIT"

[tool.poetry]
packages = [{include = "suzaku"}]

[tool.black]
line-length = 100
# A programmer who writes codes already formatted never needs a formatting tool 
# (, but someone isn't).

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
